#!/usr/bin/env python
"""
Command-line client for accessing the RIPEstat data API.

Requires Python >= 2.6
"""
import sys

from ripestat.cli import StatCLI


if __name__ == "__main__":
    sys.exit(StatCLI().main(sys.argv[1:]))
